### ISSUE TITLE
Could you share the dataset，tks

### ISSUE THREAD

**Issue by HUSTLX** [pkhungurn/talking-head-anime#1]

**Comment by pkhungurn** [comment]
If the dataset refers to the MMD models, I simply cannot. Many models have licences that do not allowed them to be redistributed.

If the dataset refers to the rendered images, then it's in a grey area. Many models' licences do not permit use in software other than MMD or its equivalents. I rendered the images using my own renderer, and I'm not sure who's going to be angry at me when I make the data public. The safe way to do this is to go through all the license and screen out troublesome models. This will take time, and I cannot promise it will ever be done.

**Comment by wzmsltw** [comment]
hi @pkhungurn , if it is not allowed to share the rendered images and MMD models, could you share renderer tools? or trained models? I would appreciate it very much.

**Comment by pkhungurn** [comment]
I'm trying to get permission to share some of the code from the company. This will include the trained model, and two small tools to use it.
