### ISSUE TITLE
how to get the eye's training data with controlling parameter between [0, 1]

### ISSUE THREAD

**Issue by CrossLee1** [pkhungurn/talking-head-anime#2]
In your blog, I just saw the process generating the training images with eyes fully open and close status.

How to get other eye's training data with controlling parameter between [0, 1], such as half open?

Thanks

**Comment by pkhungurn** [comment]
I believe the article says "For the eye and mouth controlling parameters, I sample them uniformly from the [0,1] interval." So, it almost always generate eye parameters values that are between 0 and 1.
